# Generated by Django 3.2.9 on 2021-11-23 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.BigIntegerField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='moviedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=20)),
                ('quality', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='moviefiles2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('download', models.URLField()),
                ('duration', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=20)),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=10)),
                ('poster', models.URLField()),
                ('stream', models.URLField()),
                ('trailer', models.URLField()),
                ('user_rating', models.DecimalField(decimal_places=1, max_digits=10)),
                ('views', models.IntegerField()),
                ('year', models.IntegerField()),
                ('summary', models.TextField(max_length=500)),
                ('movie_id', models.IntegerField(default=1)),
                ('slug', models.CharField(blank=True, max_length=130, null=True)),
                ('rt', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='moviefiles',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('download', models.URLField()),
                ('duration', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=20)),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=10)),
                ('poster', models.URLField()),
                ('stream', models.URLField()),
                ('trailer', models.URLField()),
                ('user_rating', models.DecimalField(decimal_places=1, max_digits=10)),
                ('views', models.IntegerField()),
                ('year', models.IntegerField()),
                ('summary', models.TextField(max_length=500)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.CharField(blank=True, max_length=130, null=True)),
                ('rt', models.IntegerField(default=1)),
                ('liked', models.ManyToManyField(related_name='movie_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovieComment',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_name', to='home.moviefiles')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.moviecomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
