# Generated by Django 3.2.8 on 2021-10-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviefiles',
            name='rt',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='moviefiles2',
            name='rt',
            field=models.IntegerField(default=1),
        ),
    ]
