# Generated by Django 3.2.8 on 2021-10-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_moviefiles2_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviefiles',
            name='slug',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
